apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-reset
  namespace: tinkerbell
  labels:
    app: cluster-reset
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: cluster-reset
    spec:
      serviceAccountName: cluster-provisioner
      hostNetwork: true
      restartPolicy: Never
      containers:
        - name: orchestrator
          image: alpine:3.19
          envFrom:
            - configMapRef:
                name: provisioner-config
          volumeMounts:
            - name: talos-secrets
              mountPath: /talos
              readOnly: true
            - name: scripts
              mountPath: /scripts
              readOnly: true
          command:
            - /bin/sh
            - /scripts/orchestrate.sh
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: talos-secrets
          secret:
            secretName: talos-secrets
        - name: scripts
          configMap:
            name: orchestrator-scripts
            defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-scripts
  namespace: tinkerbell
data:
  orchestrate.sh: |
    #!/bin/sh
    set -e
    
    # Colors
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
    
    log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
    log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
    log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
    log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
    
    # Install dependencies
    log_info "Installing dependencies..."
    apk add --no-cache curl jq kubectl wakeonlan
    
    # Download talosctl
    log_info "Downloading talosctl..."
    TALOS_VERSION="${TALOS_VERSION:-v1.12.1}"
    curl -sL "https://github.com/siderolabs/talos/releases/download/${TALOS_VERSION}/talosctl-linux-amd64" \
        -o /usr/local/bin/talosctl
    chmod +x /usr/local/bin/talosctl
    
    # Configure talosctl
    export TALOSCONFIG=/talos/talosconfig
    
    echo ""
    echo "=========================================="
    echo "  STEP 1: Cleanup old workflows"
    echo "=========================================="
    log_info "Deleting old workflows..."
    kubectl delete workflows --all -n tinkerbell 2>/dev/null || true
    log_success "Old workflows deleted"
    
    echo ""
    echo "=========================================="
    echo "  STEP 2: Wake-on-LAN"
    echo "=========================================="
    log_info "Sending WoL packets..."
    for mac in $(echo $NODE_MACS | tr ',' ' '); do
        log_info "  WoL: $mac"
        wakeonlan "$mac" || true
        sleep 1
    done
    log_success "WoL packets sent"
    
    log_info "Waiting ${WOL_WAIT_TIME}s for machines to boot..."
    sleep "$WOL_WAIT_TIME"
    
    echo ""
    echo "=========================================="
    echo "  STEP 3: Create Workflows"
    echo "=========================================="
    
    # Get hardware list
    HARDWARE_LIST=$(kubectl get hardware -n tinkerbell -o jsonpath='{.items[*].metadata.name}')
    
    for hw in $HARDWARE_LIST; do
        log_info "Creating workflow for: $hw"
        
        # Determine if controlplane or worker
        HW_IP=$(kubectl get hardware "$hw" -n tinkerbell -o jsonpath='{.spec.interfaces[0].dhcp.ip.address}')
        
        if [ "$HW_IP" = "$CONTROLPLANE_IP" ]; then
            MACHINE_CONFIG=$(cat /talos/controlplane.yaml | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}')
        else
            MACHINE_CONFIG=$(cat /talos/worker.yaml | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}')
        fi
        
        kubectl apply -f - <<EOF
    apiVersion: tinkerbell.org/v1alpha1
    kind: Workflow
    metadata:
      name: provision-${hw}
      namespace: tinkerbell
    spec:
      templateRef: talos-install
      hardwareRef: ${hw}
      hardwareMap:
        device_1: ${HW_IP}
        tinkerbell_ip: ${MANAGEMENT_IP}
        machine_config: "${MACHINE_CONFIG}"
    EOF
        
        log_success "Workflow created: provision-${hw}"
    done
    
    echo ""
    echo "=========================================="
    echo "  STEP 4: Wait for Workflows"
    echo "=========================================="
    
    TIMEOUT=$WORKFLOW_TIMEOUT
    INTERVAL=30
    ELAPSED=0
    EXPECTED_COUNT=$(echo $HARDWARE_LIST | wc -w)
    
    while [ $ELAPSED -lt $TIMEOUT ]; do
        COMPLETED=$(kubectl get workflows -n tinkerbell -o jsonpath='{.items[*].status.state}' 2>/dev/null | grep -c "STATE_SUCCESS" || echo 0)
        FAILED=$(kubectl get workflows -n tinkerbell -o jsonpath='{.items[*].status.state}' 2>/dev/null | grep -c "STATE_FAILED" || echo 0)
        
        log_info "Progress: $COMPLETED/$EXPECTED_COUNT complete, $FAILED failed"
        
        if [ "$FAILED" -gt 0 ]; then
            log_error "Some workflows failed!"
            kubectl get workflows -n tinkerbell
            exit 1
        fi
        
        if [ "$COMPLETED" -eq "$EXPECTED_COUNT" ]; then
            log_success "All workflows completed successfully!"
            break
        fi
        
        sleep $INTERVAL
        ELAPSED=$((ELAPSED + INTERVAL))
    done
    
    if [ "$COMPLETED" -ne "$EXPECTED_COUNT" ]; then
        log_error "Timeout waiting for workflows"
        kubectl get workflows -n tinkerbell
        exit 1
    fi
    
    echo ""
    echo "=========================================="
    echo "  STEP 5: Wait for Talos"
    echo "=========================================="
    
    log_info "Waiting 60s for boot to complete..."
    sleep 60
    
    log_info "Checking Talos API availability..."
    TIMEOUT=300
    ELAPSED=0
    while [ $ELAPSED -lt $TIMEOUT ]; do
        if talosctl --nodes "$CONTROLPLANE_IP" version 2>/dev/null; then
            log_success "Talos API is available!"
            break
        fi
        log_info "Waiting for Talos API... ($ELAPSED/$TIMEOUT)"
        sleep 10
        ELAPSED=$((ELAPSED + 10))
    done
    
    echo ""
    echo "=========================================="
    echo "  STEP 6: Bootstrap Kubernetes"
    echo "=========================================="
    
    log_info "Running bootstrap..."
    talosctl bootstrap --nodes "$CONTROLPLANE_IP"
    
    log_success "Bootstrap started"
    
    echo ""
    echo "=========================================="
    echo "  STEP 7: Wait for Kubernetes API"
    echo "=========================================="
    
    TIMEOUT=$BOOTSTRAP_TIMEOUT
    ELAPSED=0
    while [ $ELAPSED -lt $TIMEOUT ]; do
        if talosctl kubeconfig /tmp/kubeconfig --nodes "$CONTROLPLANE_IP" 2>/dev/null; then
            log_success "Kubeconfig retrieved!"
            break
        fi
        sleep 10
        ELAPSED=$((ELAPSED + 10))
    done
    
    echo ""
    echo "=========================================="
    echo "  STEP 8: Verify cluster"
    echo "=========================================="
    
    export KUBECONFIG=/tmp/kubeconfig
    
    log_info "Waiting for all nodes to be ready..."
    kubectl wait --for=condition=Ready nodes --all --timeout=300s || true
    
    echo ""
    kubectl get nodes -o wide
    
    echo ""
    echo "=========================================="
    echo "  STEP 9: Save kubeconfig"
    echo "=========================================="
    
    kubectl create secret generic sandbox-kubeconfig \
        --from-file=kubeconfig=/tmp/kubeconfig \
        -n tinkerbell \
        --dry-run=client -o yaml | kubectl apply -f -
    
    log_success "Kubeconfig saved to secret 'sandbox-kubeconfig'"
    
    echo ""
    echo "=========================================="
    echo "  DONE!"
    echo "=========================================="
    echo ""
    log_success "Cluster successfully deployed!"
    echo ""
    echo "To get kubeconfig:"
    echo "  kubectl get secret sandbox-kubeconfig -n tinkerbell -o jsonpath='{.data.kubeconfig}' | base64 -d > kubeconfig"
    echo ""
